In [34]:
import numpy as np

In [8]:
# ex 1
numeros = [3, 5, 9, 16, 25]
numeros_float = [float(num) for num in numeros]
print(numeros_float)


[3.0, 5.0, 9.0, 16.0, 25.0]


In [37]:
# ex 2
numeros = [1.2, -3.6, 8.99999, 16.1]

numeros_int = [int(num) for num in numeros]

print(numeros_int)

[1, -3, 8, 16]


In [18]:
# ex 3
matrizz = np.zeros((3, 9), dtype=int)

print(matrizz)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [19]:
# ex 4
matriz = np.ones((6, 7), dtype=int)

print(matriz)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [20]:
# ex 5 
matriz_identidade = np.eye(4, dtype=int)

print(matriz_identidade)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [21]:
# ex 6 
array_aleatorio = np.random.rand(5)

print(array_aleatorio)

[0.103548   0.13199256 0.97563634 0.55998338 0.88483645]


In [22]:
# ex 7
matriz_aleatoria = np.random.randint(0, 6, (3, 6))

print(matriz_aleatoria)

[[1 2 5 1 5 3]
 [3 0 2 4 1 3]
 [1 0 5 5 4 5]]


In [23]:
# ex 8 
matriz = np.array([[4, 6, 8], [-4, 3, 2], [22, -15, 12]])


valor_maximo = np.max(matriz)


print("O valor máximo da matriz é:", valor_maximo)

O valor máximo da matriz é: 22


In [24]:
# ex 9
matriz = np.array([[4, 6, 8], [-4, 3, 2], [22, -15, 12]])


valor_minimo = np.min(matriz)


print("O valor mínimo da matriz é:", valor_minimo)

O valor mínimo da matriz é: -15


In [25]:
# ex 10
matriz = np.array([[4, 6, 8], [-4, 3, 2], [22, -15, 12]])

soma_matriz = np.sum(matriz)

print("A soma dos elementos da matriz é:", soma_matriz)

A soma dos elementos da matriz é: 38


In [27]:
# ex 11
matriz = np.array([[4, 6, 8], [-4, 3, 2], [22, -15, 12]])

media_matriz = np.mean(matriz)

print("A média dos elementos da matriz é:", media_matriz)

A média dos elementos da matriz é: 4.222222222222222


In [33]:
# ex 12
arr = np.array([13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12])

print("O 4º elemento do array é:", arr[3])

O 4º elemento do array é: 8


In [38]:
# EX 13 
print("Os 3 últimos elementos do array são:", arr[-3:])


Os 3 últimos elementos do array são: [10 56 12]


In [39]:
# EX 14
print("Elementos a partir da posição 2:", arr[2:])

Elementos a partir da posição 2: [ 6  8 23 15  3 90  4 10 56 12]


In [40]:
# ex 15
print("Elementos entre o 2º e o 6º:", arr[1:6])

Elementos entre o 2º e o 6º: [-2  6  8 23 15]


In [41]:
# ex 16
print("Array [23, 15, 3, 90]:", arr[4:8])

Array [23, 15, 3, 90]: [23 15  3 90]


In [42]:
# ex 17
matriz = np.array([
    [1, 3, 16, -25, 14],
    [2, 0, 10, 5, 17],
    [19, 4, 8, 15, 13],
    [7, 12, -5, 14, 0]
])
print("3ª linha da matriz:", matriz[2])

3ª linha da matriz: [19  4  8 15 13]


In [43]:
# ex 18
print("4ª coluna da matriz:", matriz[:, 3])


4ª coluna da matriz: [-25   5  15  14]


In [44]:
# ex 19 
print("Elemento de valor 10:", matriz[1, 2])


Elemento de valor 10: 10


In [45]:
# ex 20
submatriz = matriz[1:3, 1:4]
print("Submatriz:\n", submatriz)

Submatriz:
 [[ 0 10  5]
 [ 4  8 15]]


In [46]:
# ex 21

matriz = np.array([
    [2, -1, 15, 24],
    [-3, 18, 4, 25],
    [9, 10, -13, 7]
])


nova_matriz = np.where(matriz % 2 == 0, 2, 1)


print(nova_matriz)


[[2 1 1 2]
 [1 2 2 1]
 [1 2 1 1]]
